stages:
  split_data:
    cmd: python src/data_split.py
    deps:
      - src/data_split.py
      - data/raw/
      - params.yaml
    outs:
      - data/train/
      - data/val/
      - data/test/

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/train/
      - data/val/
      - params.yaml
    outs:
      - runs/train/weights/best.pt

  evaluate:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - runs/train/weights/best.pt
      - params.yaml
    outs:
      - runs/predictions/
