stages:
  split_data:
    cmd: python src/data_split.py
    deps:
      - src/data_split.py
      - data/raw/images
      - data/raw/labels
    outs:
      - data/processed/train
      - data/processed/val
      - data/processed/test


  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train/
      - data/processed/val/
      - params.yaml
    outs:
      - runs/detect/train/weights/best.pt

  evaluate:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - runs/detect/train/weights/best.pt
      - params.yaml
    outs:
      - runs/predictions/
