base:
  random_seed: 42

data_split:
  valid_pct: 0.1
  test_pct: 0.1


train:
  valid_pct: 0.1
  arch: yolov8n
  img_size: 640
  batch_size: 8
  fine_tune_args:
    epochs: 10
    base_lr: 0.01

evaluate:
  n_samples_to_save: 10
