name: sky-run
resources:
  accelerators: T4:1
  cloud: aws
  region: us-east-2
workdir: .
file_mounts: 
  # if you want be able to interact with your git repos 
  ~/.ssh/id_rsa: ~/.ssh/id_rsa
  ~/.ssh/id_rsa.pub: ~/.ssh/id_rsa.pub
  ~/.gitconfig: ~/.gitconfig
setup: | # only executed on `sky launch`
  pip install --upgrade pip
  pip install -r requirements.txt
  # Below is optional nvtop installation if you want to monitor GPU usage
  sudo apt update -y
  sudo apt install libdrm-dev libsystemd-dev -y
  sudo apt install cmake libncurses5-dev libncursesw5-dev git -y 
  git clone https://github.com/Syllo/nvtop.git
  mkdir -p nvtop/build && cd nvtop/build
  sudo cmake .. -DNVIDIA_SUPPORT=ON -DAMDGPU_SUPPORT=ON -DINTEL_SUPPORT=ON
  sudo make install

run: | # executed on `sky launch` or `sky exec`
  cd ~/sky_workdir
  dvc pull
  dvc exp run --pull --allow-missing
  dvc exp push origin